[env:nanoatmega328]
platform = atmelavr@5.3.0
board = nanoatmega328
framework = arduino
monitor_speed = 9600
build_src_flags =
  -Wall
  -Wextra
  -Werror
lib_deps =
  paulstoffregen/OneWire@2.3.8
  https://github.com/vdwulp/iButtonTag.git#ea476442647576be70399e6b5e7265acf7fea6df
